const LANG_EN_MAPS = {
    TITLE: "Waves",
    EXPLORE: "Explore",
    DIRECTIONS: "Directions",
    GAME: "Game",
    SEARCH_PLACEHOLDER: "Search for a place or address",
    STARTING_POINT_PLACEHOLDER: "Starting point",
    DESTINATION_PLACEHOLDER: "Choose destination",
    DRIVE: "Drive",
    WALK: "Walk",
    CYCLE: "Cycle",
    SEARCH_RESULTS_TITLE: "Search Results",
    ROUTE_TITLE: "Route ({duration} min)",
    ROUTE_SUBTITLE: "{distance} km",
    GAME_SOON: "Game mode is coming soon!",
    API_KEY_MISSING: "API key is missing for directions.",
    GEOLOCATION_UNSUPPORTED: "Geolocation is not supported.",
    LOCATION_UNAVAILABLE: "Unable to retrieve your location.",
    ROUTE_ERROR: "Could not get route: {error}",
    NO_RESULTS_FOUND: "No results found."
};

const LANG_JP_MAPS = {
    TITLE: "Waves",
    EXPLORE: "探索",
    DIRECTIONS: "経路",
    GAME: "ゲーム",
    SEARCH_PLACEHOLDER: "場所や住所を検索",
    STARTING_POINT_PLACEHOLDER: "出発地",
    DESTINATION_PLACEHOLDER: "目的地を選択",
    DRIVE: "車",
    WALK: "徒歩",
    CYCLE: "自転車",
    SEARCH_RESULTS_TITLE: "検索結果",
    ROUTE_TITLE: "経路（{duration}分）",
    ROUTE_SUBTITLE: "{distance} km",
    GAME_SOON: "ゲームモードは近日公開予定です！",
    API_KEY_MISSING: "経路案内にAPIキーが必要です。",
    GEOLOCATION_UNSUPPORTED: "ジオロケーションはサポートされていません。",
    LOCATION_UNAVAILABLE: "現在地を取得できません。",
    ROUTE_ERROR: "経路を取得できませんでした：{error}",
    NO_RESULTS_FOUND: "結果が見つかりません。"
};

const LANG_DE_MAPS = {
    TITLE: "Waves",
    EXPLORE: "Erkunden",
    DIRECTIONS: "Route",
    GAME: "Spiel",
    SEARCH_PLACEHOLDER: "Ort oder Adresse suchen",
    STARTING_POINT_PLACEHOLDER: "Startpunkt",
    DESTINATION_PLACEHOLDER: "Ziel wählen",
    DRIVE: "Fahren",
    WALK: "Gehen",
    CYCLE: "Radfahren",
    SEARCH_RESULTS_TITLE: "Suchergebnisse",
    ROUTE_TITLE: "Route ({duration} Min.)",
    ROUTE_SUBTITLE: "{distance} km",
    GAME_SOON: "Spielmodus kommt bald!",
    API_KEY_MISSING: "API-Schlüssel für Wegbeschreibung fehlt.",
    GEOLOCATION_UNSUPPORTED: "Geolokalisierung wird nicht unterstützt.",
    LOCATION_UNAVAILABLE: "Standort konnte nicht abgerufen werden.",
    ROUTE_ERROR: "Route konnte nicht abgerufen werden: {error}",
    NO_RESULTS_FOUND: "Keine Ergebnisse gefunden."
};

const LANG_ES_MAPS = {
    TITLE: "Waves",
    EXPLORE: "Explorar",
    DIRECTIONS: "Direcciones",
    GAME: "Juego",
    SEARCH_PLACEHOLDER: "Buscar un lugar o dirección",
    STARTING_POINT_PLACEHOLDER: "Punto de partida",
    DESTINATION_PLACEHOLDER: "Elegir destino",
    DRIVE: "Coche",
    WALK: "Caminar",
    CYCLE: "Bicicleta",
    SEARCH_RESULTS_TITLE: "Resultados de búsqueda",
    ROUTE_TITLE: "Ruta ({duration} min)",
    ROUTE_SUBTITLE: "{distance} km",
    GAME_SOON: "¡El modo de juego llegará pronto!",
    API_KEY_MISSING: "Falta la clave de API para las direcciones.",
    GEOLOCATION_UNSUPPORTED: "La geolocalización no es compatible.",
    LOCATION_UNAVAILABLE: "No se puede obtener tu ubicación.",
    ROUTE_ERROR: "No se pudo obtener la ruta: {error}",
    NO_RESULTS_FOUND: "No se encontraron resultados."
};

const LANG_KO_MAPS = {
    TITLE: "Waves",
    EXPLORE: "탐색",
    DIRECTIONS: "길찾기",
    GAME: "게임",
    SEARCH_PLACEHOLDER: "장소 또는 주소 검색",
    STARTING_POINT_PLACEHOLDER: "출발지",
    DESTINATION_PLACEHOLDER: "목적지 선택",
    DRIVE: "자동차",
    WALK: "도보",
    CYCLE: "자전거",
    SEARCH_RESULTS_TITLE: "검색 결과",
    ROUTE_TITLE: "경로 ({duration}분)",
    ROUTE_SUBTITLE: "{distance}km",
    GAME_SOON: "게임 모드는 곧 제공될 예정입니다!",
    API_KEY_MISSING: "길찾기를 위한 API 키가 없습니다.",
    GEOLOCATION_UNSUPPORTED: "위치 정보가 지원되지 않습니다.",
    LOCATION_UNAVAILABLE: "위치를 가져올 수 없습니다.",
    ROUTE_ERROR: "경로를 가져올 수 없습니다: {error}",
    NO_RESULTS_FOUND: "결과를 찾을 수 없습니다."
};

const LANG_ZH_MAPS = {
    TITLE: "Waves",
    EXPLORE: "探索",
    DIRECTIONS: "路线",
    GAME: "游戏",
    SEARCH_PLACEHOLDER: "搜索地点或地址",
    STARTING_POINT_PLACEHOLDER: "起点",
    DESTINATION_PLACEHOLDER: "选择目的地",
    DRIVE: "驾车",
    WALK: "步行",
    CYCLE: "骑行",
    SEARCH_RESULTS_TITLE: "搜索结果",
    ROUTE_TITLE: "路线（{duration}分钟）",
    ROUTE_SUBTITLE: "{distance}公里",
    GAME_SOON: "游戏模式即将推出！",
    API_KEY_MISSING: "缺少用于导航的API密钥。",
    GEOLOCATION_UNSUPPORTED: "不支持地理定位。",
    LOCATION_UNAVAILABLE: "无法获取您的位置。",
    ROUTE_ERROR: "无法获取路线：{error}",
    NO_RESULTS_FOUND: "未找到结果。"
};
